behaviors:
  BasicFindTarget:
    trainer_type: ppo
    hyperparameters:
      batch_size: 500
      buffer_size: 5000
      learning_rate: 0.0002
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: linear
    threaded: true
    network_settings:
      normalize: false
      hidden_units: 20
      num_layers: 1
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.5
        demo_path: C:\Projects\Machine-Learning\MLTestArea\MLTest2\Demos\BasicFindTarget.demo
    behavioral_cloning:
      strength: 0.9
      demo_path: C:\Projects\Machine-Learning\MLTestArea\MLTest2\Demos\BasicFindTarget.demo
    max_steps: 2000000
    time_horizon: 3
    summary_freq: 20000