behaviors:
  BasicFindTarget:
    trainer_type: ppo
    hyperparameters:
      batch_size: 500
      buffer_size: 5000
      learning_rate: 0.0002
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: linear
    threaded: true
    network_settings:
      normalize: false
      hidden_units: 100
      num_layers: 1
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.03
    max_steps: 20000000
    time_horizon: 64
    summary_freq: 20000