behaviors:
  Explorer:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 5000
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: linear
    threaded: true
    network_settings:
      normalize: false
      hidden_units: 20
      num_layers: 1
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.9
    max_steps: 1000000
    time_horizon: 3
    summary_freq: 20000